AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model in keras model
BATCH_SIZE: 16 
INCLUDE_TOP: False 
EPOCHS: 2
CLASSES: 2  # 2 classes: cancer and normal
WEIGHTS: imagenet
LEARNING_RATE: 0.02